"use client";
import { useState } from "react";
type Row = Record<string, any>;
export function AdminClient({ authenticated, businesses, plans, payments }: { authenticated: boolean; businesses: Row[]; plans: Row[]; payments: Row[] }) {
  const [message,setMessage]=useState(""); const [code,setCode]=useState("");
  async function login(form:FormData){const response=await fetch("/api/v1/admin/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});if(response.ok)location.reload();else setMessage("Login failed")}
  async function request(url:string,method:string,body?:unknown){const response=await fetch(url,{method,headers:{"content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok){setMessage(result.message);return null}if(result.data?.activationCode)setCode(result.data.activationCode);setMessage("Saved successfully");return result.data}
  async function savePlan(form:FormData){const raw=Object.fromEntries(form);const saved=await request("/api/v1/admin/plans","PUT",{key:raw.key,name:raw.name,monthlyPrice:Number(raw.monthlyPrice),annualPrice:Number(raw.annualPrice),userLimit:Number(raw.userLimit),features:String(raw.features||"").split(",").map(v=>v.trim()).filter(Boolean),addOns:[]});if(saved)location.reload()}
  async function createBusiness(form:FormData){const raw=Object.fromEntries(form);const saved=await request("/api/v1/admin/businesses","POST",{name:raw.name,externalReference:raw.externalReference,planKey:raw.planKey,billingType:raw.billingType,paidThrough:raw.paidThrough?new Date(String(raw.paidThrough)+"T23:59:59+05:00").toISOString():null,negotiatedPrice:raw.negotiatedPrice?Number(raw.negotiatedPrice):null,productEdition:"current",grantedFeatures:[],grantedAddOns:[],userLimit:Number(raw.userLimit||1),agreementNotes:raw.agreementNotes||""});if(saved)location.reload()}
  if(!authenticated)return <main className="shell"><section className="card" style={{maxWidth:420,margin:"80px auto"}}><h1>Administrator login</h1><form action={login} className="stack"><input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" required/><input name="totp" inputMode="numeric" placeholder="6-digit authenticator code" required/><button>Sign in</button>{message&&<div className="notice">{message}</div>}</form></section></main>;
  return <main className="shell">
    <div className="bar"><div><div className="brand">PANDAS Control Plane</div><div className="muted">Businesses, contracts, installations and payments</div></div><button onClick={async()=>{await fetch("/api/v1/admin/session",{method:"DELETE"});location.reload()}}>Sign out</button></div>
    {message&&<p className="notice">{message}{code&&<> — activation code: <strong>{code}</strong></>}</p>}
    <div className="grid cols"><section className="card"><h2>Businesses</h2><p className="muted">{businesses.length} configured</p></section><section className="card"><h2>Plans</h2><p className="muted">{plans.length} configured</p></section><section className="card"><h2>Payments</h2><p className="muted">{payments.length} recent orders</p></section></div>
    <div className="grid cols" style={{marginTop:16}}>
      <section className="card"><h2>Configure plan</h2><form action={savePlan} className="stack"><select name="key"><option value="basic">Basic</option><option value="premium">Premium</option><option value="enterprise">Enterprise</option></select><input name="name" placeholder="Display name" required/><input name="monthlyPrice" type="number" min="0" placeholder="Monthly PKR" required/><input name="annualPrice" type="number" min="0" placeholder="Annual PKR" required/><input name="userLimit" type="number" min="1" placeholder="User limit" required/><input name="features" placeholder="Feature keys, comma separated"/><button>Save plan</button></form></section>
      <section className="card"><h2>Add client contract</h2><form action={createBusiness} className="stack"><input name="name" placeholder="Business name" required/><input name="externalReference" placeholder="Internal reference"/><select name="planKey">{plans.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</select><select name="billingType"><option value="monthly">Monthly</option><option value="annual">Annual</option><option value="perpetual">Perpetual</option><option value="complimentary">Complimentary</option></select><input name="paidThrough" type="date"/><input name="negotiatedPrice" type="number" min="0" placeholder="Negotiated price (optional)"/><input name="userLimit" type="number" min="1" defaultValue="1"/><textarea name="agreementNotes" placeholder="Agreement notes"/><button disabled={!plans.length}>Create client</button></form></section>
    </div>
    <section className="card" style={{marginTop:16,overflowX:"auto"}}><h2>Client contracts</h2><table><thead><tr><th>Business</th><th>Plan</th><th>Agreement</th><th>Status</th><th>Paid through</th><th>Price</th><th>Actions</th></tr></thead><tbody>{businesses.map(b=><tr key={b._id}><td>{b.name}</td><td>{b.planKey}</td><td><span className="tag">{b.billingType}</span></td><td>{b.configuredStatus}</td><td>{b.billingType==="perpetual"?"Lifetime":b.paidThrough?new Date(b.paidThrough).toLocaleDateString():"Not set"}</td><td>{b.negotiatedPrice??"Standard"}</td><td><button onClick={()=>request(`/api/v1/admin/businesses/${b._id}/activation-code`,"POST")}>Activation code</button>{b.billingType!=="perpetual"&&<button style={{marginLeft:6}} onClick={async()=>{const reason=prompt("Reason for manual renewal");if(reason){const saved=await request(`/api/v1/admin/businesses/${b._id}/renew`,"POST",{terms:1,reason,complimentary:false});if(saved)location.reload()}}}>Renew</button>}{b.configuredStatus==="suspended"?<button style={{marginLeft:6}} onClick={async()=>{const reason=prompt("Reason for reactivation");if(reason){const saved=await request(`/api/v1/admin/businesses/${b._id}`,"PATCH",{configuredStatus:"active",agreementNotes:reason});if(saved)location.reload()}}}>Reactivate</button>:<button className="danger" style={{marginLeft:6}} onClick={async()=>{const reason=prompt("Reason for suspension");if(reason){const saved=await request(`/api/v1/admin/businesses/${b._id}`,"PATCH",{configuredStatus:"suspended",agreementNotes:reason});if(saved)location.reload()}}}>Suspend</button>}</td></tr>)}</tbody></table></section>
    <section className="card" style={{marginTop:16,overflowX:"auto"}}><h2>Recent payment orders</h2><table><thead><tr><th>Order</th><th>Status</th><th>Amount</th><th>Created</th></tr></thead><tbody>{payments.map(p=><tr key={p._id}><td>{p.orderId}</td><td>{p.status}</td><td>PKR {p.amount}</td><td>{new Date(p.createdAt).toLocaleString()}</td></tr>)}</tbody></table></section>
  </main>;
}
